### ISSUE TITLE
Add demo / test pipeline for LL1_50words

### ISSUE THREAD

**Issue by kmax12** [Featuretools/ta1-primitives#17]

**Comment by thehomebrewnerd** [comment]
Added a test pipeline in PR #23. This will run the full test with kfolds if executed manually from the command line with `python3 pipeline_tests/test_LL1_50words.py`, but not if run with the `run_pipelines.sh` shell script.

**Comment by thehomebrewnerd** [comment]
The pipeline for this test needs to be updated. Currently the input data is just a list of time series files, so feature tools doesn't build any meaningful features. We need to add additional pipeline steps to do some processing on the individual time series files in the `timeseries` directory to create features that can be used for classification.

**Comment by thehomebrewnerd** [comment]
This pipeline was updated and fixed in PR #31
