### ISSUE TITLE
Please make package dependencies more explict

### ISSUE THREAD

**Issue by mitar** [Featuretools/ta1-primitives#3]
In this primitive you have a dependency `'featuretools>=0.2.0`. But now that `0.3.0` version is available, it gets installed into the Docker image. But 0.3.0 version requires pandas 0.23 so things break.

Please when you are submitting a primitive, make sure that packages your primitive depends are fixed as much as possible as well, so that builds of Docker images do not break in the future.

I will be disabling your primitive annotations for now for `v2018.7.10` version.

**Comment by csala** [comment]
Done in #4
